### ISSUE TITLE
Is it possible to specify IoT Edge Version?

### ISSUE THREAD

**Issue by sihbher** [Azure/iot-edge-config#43]
Would be great to be able to specify a specific IoT Edge version to deploy. or is it possible now?

**Comment by marianan** [comment]
thanks for your feedback @sihbher . Currently IoTEdgeConfig installs Edge Runtime 1.2. It would help us to understand better your use case - which version of Edge Runtime is needed and why is 1.2 not suitable?

**Comment by sihbher** [comment]
Hi, in my role sometimes have to try to reproduce errors/bugs/strange behaviour in customer/partner environments and they sometimes don't have the latest version, and propose only to update to latest version needs to be supported with facts because it could imply to do changes in a production environments.

**Comment by marianan** [comment]
@sihbher thank you for sharing your use case. At this time I am closing this issue as we don't have immediate plans for offering earlier versions support.
